export enum Urls {
  AKREM_LOGO_ICON = '/akrem_logo.png',
  AKREM_LOGO_TEXT = '/akrem_logo_text.png',
  AKREM_BG_LOGO = '/akrem_bg_logo.png',
  FACEBOOK_LOGO = '/facebook.svg',
  GOOGLE_LOGO = '/google.svg',
  DOCTOR_GIVE_TABLETS_PNG = '/doctor_give_tablets.png',
  Home_PNG = '/home_picture.png',
  MAP_BG = '/map_bg.png',
  ANDROID_LOGO = '/android_logo.png',
  DOWNLOAD_FOR_ANDROID = '/download_for_android.png',
  DOWNLOAD_MOBILE_APP = '/download_for_android.png',
  HOME_PAGE = '/',
  MEMBER_PAGE = '/member',
  CART_PAGE = '/cart',
  PROFILE_PAGE = '/profile/[profile]',
  CONTACT_PAGE = '/contact',
  DONATE_PAGE = '/donate',
  DONATE_CONFIRM_PAGE = '/donate/checkout',
  ORDER_PAGE = '/order',
  ORDER_CONFIRM_PAGE = '/order/checkout',
  RESET_PAGE = '/reset',
  CONFIRM_PAGE = '/confirm',
  BOXES = '/boxes',
}
